[package]
name = "aggregate_types"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["voidentente <voidentente@paranoici.org>"]
repository = "https://github.com/voidentente/aggregate"
description = "Aggregate attributes of structs for runtime"

[features]
serde = ["debug", "dep:serde"]
debug = ["syn/extra-traits"]

[dependencies.syn]
version = "1.0.107"

[dependencies.serde]
version = "1.0.151"
optional = true